# Generated by Django 4.2.11 on 2024-04-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docappontment',
            old_name='name',
            new_name='doctor',
        ),
    ]
